# Generated by Django 4.0.2 on 2022-03-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('salary', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField()),
            ],
        ),
    ]
