# Generated by Django 4.0.2 on 2022-03-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeModel',
            new_name='Employee',
        ),
    ]
